### ISSUE TITLE
AmazonEC2FullAccess seems too broad

### ISSUE THREAD

**Issue by Jonty** [rpetrich/patrolaroid#6]
This is absolutely brilliant, however `AmazonEC2FullAccess` seems like a very wide policy to apply.

It looks like only the following calls need to be in the policy, but I may have missed some:
```
AttachVolume
CreateVolume
DeleteVolume
DescribeVolumes
DetachVolume
CreateSnapshot
DescribeSnapshots
```

A rough policy might look like this, although it would be nice to constrain actions such as `Delete` to volumes created by patrolaroid. Perhaps by apply a tag to created volumes and limit mutation actions to that tag?

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1622650196578",
      "Action": [
        "ec2:AttachVolume",
        "ec2:CreateSnapshot",
        "ec2:CreateVolume",
        "ec2:DeleteVolume",
        "ec2:DescribeSnapshots",
        "ec2:DescribeVolumes",
        "ec2:DetachVolume"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
```

**Comment by swagitda** [comment]
Thanks for doing the work for us! 🖤  Your suggested policy is now documented as the recommended one in the Getting Started guide and located here: https://github.com/rpetrich/patrolaroid/blob/main/docs/recommended-iam-policy.md
